### ISSUE TITLE
general enquiry

### ISSUE THREAD

**Issue by DavidNorman** [LittleFox94/gotoshock#1]
is this project the beginnings of something that can control a pishock device locally, without requiring the internet connection and extra box?  if so i am interested to know what your plans are.

**Comment by LittleFox94** [comment]
Hi,

kinda - it's another implementation of the protocol between the shockers (which are widely available as "pet training helpers" (don't you dare actually use them on pets!)) and the remote. There is enough code to run it on a Raspberry Pi with a simple RF module (e.g. https://www.ebay.de/itm/255283295144) connected to one of its GPIOs and I also plan to have support for different I/O drivers and federation, so you can chain them together and build links with that you can safely share with other people (with configured limits and all)

... and all that, just because we happened to have a shocker already that is pretty much the same as the ones sold by PiShock but PiShock not selling the remote only :upside_down_face:

**Comment by DavidNorman** [comment]
it does seem very barbaric to use them on a non-consenting animal. 

so i could take your code - extract the RF control part, and rig up a Raspberry Pi and that RF module to do control via the Pi's USB (pretending to be a serial port or something) ?    Or even one of this BLE processors.   Is it a simple protocol to contol thise RF modules with the GPIO pin?

**Comment by LittleFox94** [comment]
What the code here implements is

1. an implementation of the binary protocol used to talk to those shockers
2. helper code to output messages of this binary protocol via different means
    - though only "Raspi GPIO pin with a RF module connected to it" is currently implemented
    - I want to add more sensible "drivers" though, ideas welcome!
3. a server to receive messages via HTTP requests and then output them via a configured driver(-stack)

You wouldn't have to extract any code if you only want a subset of those features, but could just use that subset as a package - I try to have sensible interfaces and abstractions and not have this one big interconnected mess for the server.

Using the server, you could just run that on a Raspi and connect a RF module to it and then remotely control from whatever internet connected device you'd like - the server running on the Raspi connecting the shocker to the internet ("internet" being flexible here, can be local-network-only of course)

**Comment by DavidNorman** [comment]
thanks.  i managed to make my own little version.
